# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='capter',
            new_name='chapter',
        ),
        migrations.AlterField(
            model_name='art',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Chapter'),
        ),
    ]
