# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170603_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='detail',
            field=models.TextField(max_length=300, verbose_name='詳細'),
        ),
    ]
