# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_artimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Art'),
        ),
    ]
