# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_artimage_art'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='artimage',
            options={'verbose_name': '画像', 'verbose_name_plural': '画像'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '章', 'verbose_name_plural': '章'},
        ),
    ]
