# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20171202_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artimage',
            old_name='displayname',
            new_name='displayName',
        ),
    ]
