# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20171202_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='minne_url',
            field=models.URLField(blank=True, null=True, verbose_name='ミンネのURL'),
        ),
    ]
