# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_art_minne_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='作者のコメント'),
        ),
        migrations.AddField(
            model_name='art',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='売れたか'),
        ),
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='値段'),
        ),
        migrations.AddField(
            model_name='art',
            name='price_sold',
            field=models.IntegerField(default=1000, verbose_name='実際売った値段'),
        ),
        migrations.AlterField(
            model_name='art',
            name='detail',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='詳細'),
        ),
    ]
