# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20171211_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='is_in_dark',
            field=models.BooleanField(default=True, verbose_name='暗闇'),
        ),
    ]
