# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20180106_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': 'art', 'verbose_name_plural': 'art'},
        ),
        migrations.AddField(
            model_name='artimage',
            name='is_topPageImage',
            field=models.BooleanField(default=False, verbose_name='トップページ'),
        ),
    ]
