# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20180216_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='章'),
        ),
    ]
