# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名前'),
        ),
    ]
