# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20180216_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='is_itemlist',
            field=models.BooleanField(default=True, verbose_name='アイテムリストに載せる'),
        ),
    ]
