# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='題名')),
                ('content', models.TextField(verbose_name='本文')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='RoughTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': '大タグ',
                'verbose_name_plural': '大タグ',
            },
        ),
        migrations.CreateModel(
            name='SmallTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.RoughTag', verbose_name='大カテゴリ')),
            ],
            options={
                'verbose_name': '小タグ',
                'verbose_name_plural': '小タグ',
            },
        ),
    ]
