# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.RenameModel(
            old_name='RoughTag',
            new_name='RoughCategory',
        ),
        migrations.RenameModel(
            old_name='SmallTag',
            new_name='SmallCategory',
        ),
        migrations.AlterModelOptions(
            name='roughcategory',
            options={'verbose_name': '大カテゴリ', 'verbose_name_plural': '大カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='smallcategory',
            options={'verbose_name': '小カテゴリ', 'verbose_name_plural': '小カテゴリ'},
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SmallCategory', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_html_source',
            field=models.BooleanField(default=False, verbose_name='HTMLで記述した'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='公開OK'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_rst_source',
            field=models.BooleanField(default=False, verbose_name='reStructuredTextで記述した'),
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumnail/', verbose_name='サムネイル'),
        ),
        migrations.AddField(
            model_name='content',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='タグ'),
        ),
    ]
